chrome_driver_path_windows: 'C:/Users/ymanral/Chromedriver/chromedriver.exe'
chrome_driver_path_jenkins: '/usr/local/bin/chromedriver'
username: 'root'
password: 'root'
account_name: 'chaita'
task_name: 'New Task'
ffcrm_server_link: 'http://54.201.36.55:3000/'
